import type { LegalDocumentType, Locale } from './locales';

type LocalizedLocale = Exclude<Locale, 'en'>;

export type LegalBlock =
  | { type: 'h2' | 'h3' | 'p'; html: string }
  | { type: 'ul'; items: string[] };

export interface LocalizedLegalDocument {
  lastUpdated?: string;
  blocks: LegalBlock[];
}

type LocalizedLegalContent = Record<LocalizedLocale, Record<LegalDocumentType, LocalizedLegalDocument>>;

const contact = '<a href="mailto:support@esociate.it.com">support@esociate.it.com</a>';
const termsContact = '<a href="mailto:terms@esociate.it.com">terms@esociate.it.com</a>';
const expo = '<a href="https://expo.dev/privacy" target="_blank" rel="noopener noreferrer">Expo</a>';
const revenueCat =
  '<a href="https://www.revenuecat.com/privacy" target="_blank" rel="noopener noreferrer">RevenueCat</a>';

export const localizedLegalContent: LocalizedLegalContent = {
  de: {
    privacyPolicy: {
      lastUpdated: '17. Marz 2026',
      blocks: [
        {
          type: 'p',
          html: 'Diese Datenschutzerklarung gilt fur die mobile Revera-App (nachfolgend "Anwendung"), die von ESOciate - Eser Kayali (nachfolgend "Dienstanbieter") als kommerzieller Dienst entwickelt wurde. Dieser Dienst wird "wie besehen" bereitgestellt.',
        },
        { type: 'h2', html: 'Welche Informationen erfasst die Anwendung und wie werden sie genutzt?' },
        {
          type: 'p',
          html: 'Die Anwendung erfasst Informationen, die du beim Herunterladen und Registrieren der Anwendung angibst. Eine Registrierung beim Dienstanbieter ist nicht zwingend erforderlich. Bitte beachte jedoch, dass einige Funktionen der Anwendung ohne Registrierung moglicherweise nicht nutzbar sind.',
        },
        {
          type: 'p',
          html: 'Der Dienstanbieter kann die von dir bereitgestellten Informationen außerdem verwenden, um dich gelegentlich mit wichtigen Informationen, erforderlichen Hinweisen und Marketingaktionen zu kontaktieren.',
        },
        { type: 'h2', html: 'Welche Informationen erfasst die Anwendung automatisch?' },
        {
          type: 'p',
          html: 'Die Anwendung kann bestimmte Informationen automatisch erfassen, einschließlich, aber nicht beschrankt auf den Typ deines mobilen Gerats, die eindeutige Gerate-ID, die IP-Adresse, das mobile Betriebssystem, den Typ des mobilen Internetbrowsers und Informationen daruber, wie du die Anwendung nutzt.',
        },
        { type: 'h2', html: 'Erfasst die Anwendung genaue Echtzeit-Standortdaten des Gerats?' },
        { type: 'p', html: 'Diese Anwendung erfasst keine genauen Standortinformationen deines mobilen Gerats.' },
        { type: 'h2', html: 'Verwendet die Anwendung Technologien der Kunstlichen Intelligenz (KI)?' },
        {
          type: 'p',
          html: 'Die Anwendung verwendet keine Technologien der Kunstlichen Intelligenz (KI), um deine Daten zu verarbeiten oder Funktionen bereitzustellen.',
        },
        { type: 'h2', html: 'Erhalten Dritte Einsicht in oder Zugriff auf Informationen der Anwendung?' },
        {
          type: 'p',
          html: 'Nur aggregierte, anonymisierte Daten werden regelmaßig an externe Dienste ubermittelt, um den Dienstanbieter bei der Verbesserung der Anwendung und des Dienstes zu unterstutzen. Der Dienstanbieter kann deine Informationen in der in dieser Datenschutzerklarung beschriebenen Weise an Dritte weitergeben.',
        },
        {
          type: 'p',
          html: 'Bitte beachte, dass die Anwendung Drittanbieterdienste nutzt, die eigene Datenschutzrichtlinien fur den Umgang mit Daten haben. Die Datenschutzrichtlinien der verwendeten Drittanbieter findest du hier:',
        },
        { type: 'ul', items: [expo, revenueCat] },
        {
          type: 'p',
          html: 'Der Dienstanbieter kann bereitgestellte und automatisch erfasste Informationen offenlegen:',
        },
        {
          type: 'ul',
          items: [
            'wenn dies gesetzlich vorgeschrieben ist, etwa zur Erfullung einer Vorladung oder eines vergleichbaren rechtlichen Verfahrens;',
            'wenn er nach Treu und Glauben davon ausgeht, dass die Offenlegung erforderlich ist, um seine Rechte zu schutzen, deine Sicherheit oder die Sicherheit anderer zu schutzen, Betrug zu untersuchen oder auf eine behordliche Anfrage zu reagieren;',
            'gegenuber vertrauenswurdigen Dienstleistern, die in seinem Auftrag arbeiten, die offengelegten Informationen nicht eigenstandig nutzen und sich zur Einhaltung der in dieser Datenschutzerklarung beschriebenen Regeln verpflichtet haben.',
          ],
        },
        { type: 'h2', html: 'Welche Widerspruchsrechte habe ich?' },
        {
          type: 'p',
          html: 'Du kannst jede weitere Datenerfassung durch die Anwendung beenden, indem du die Anwendung deinstallierst. Nutze dafur die Standard-Deinstallationsverfahren deines mobilen Gerats oder des jeweiligen App-Marktplatzes.',
        },
        { type: 'h2', html: 'Wie lange werden Daten gespeichert und wie kannst du deine Informationen verwalten?' },
        {
          type: 'p',
          html: `Der Dienstanbieter speichert von Nutzern bereitgestellte Daten, solange du die Anwendung nutzt und fur einen angemessenen Zeitraum danach. Automatisch erfasste Informationen werden bis zu 24 Monate gespeichert und danach moglicherweise aggregiert aufbewahrt. Wenn du die Loschung von Daten wunschst, die du uber die Anwendung bereitgestellt hast, kontaktiere den Dienstanbieter unter ${contact}. Wir antworten innerhalb angemessener Zeit. Bitte beachte, dass einige oder alle bereitgestellten Daten fur die ordnungsgemaße Funktion der Anwendung erforderlich sein konnen.`,
        },
        { type: 'h2', html: 'Wie behandelt die Anwendung den Datenschutz von Kindern?' },
        {
          type: 'p',
          html: 'Der Dienstanbieter nutzt die Anwendung nicht wissentlich, um Daten von Kindern unter 13 Jahren zu erheben oder diese zu vermarkten.',
        },
        {
          type: 'p',
          html: `Die Anwendung richtet sich nicht an Personen unter 13 Jahren. Der Dienstanbieter erhebt wissentlich keine personenbezogenen Daten von Kindern unter 13 Jahren. Falls der Dienstanbieter feststellt, dass ein Kind unter 13 Jahren personenbezogene Daten bereitgestellt hat, werden diese umgehend geloscht. Wenn du Elternteil oder Erziehungsberechtigter bist und weißt, dass dein Kind uns personenbezogene Daten bereitgestellt hat, kontaktiere den Dienstanbieter unter ${contact}, damit die erforderlichen Maßnahmen ergriffen werden konnen.`,
        },
        { type: 'h2', html: 'Wie werden deine Informationen geschutzt?' },
        {
          type: 'p',
          html: 'Der Dienstanbieter legt Wert auf den Schutz der Vertraulichkeit deiner Informationen. Er setzt physische, elektronische und organisatorische Schutzmaßnahmen ein, um verarbeitete und gespeicherte Informationen zu schutzen. Der Zugriff ist auf autorisierte Mitarbeitende und Auftragnehmer beschrankt, die diese Informationen fur Betrieb, Entwicklung oder Verbesserung der Anwendung benotigen. Kein Sicherheitssystem kann jedoch alle moglichen Sicherheitsverletzungen verhindern.',
        },
        { type: 'h2', html: 'Wie wirst du uber Anderungen dieser Datenschutzerklarung informiert?' },
        {
          type: 'p',
          html: 'Diese Datenschutzerklarung kann aus beliebigen Grunden von Zeit zu Zeit aktualisiert werden. Der Dienstanbieter informiert dich uber Anderungen, indem diese Seite mit der neuen Datenschutzerklarung aktualisiert wird. Du solltest diese Datenschutzerklarung regelmaßig auf Anderungen prufen; die fortgesetzte Nutzung gilt als Zustimmung zu allen Anderungen.',
        },
        { type: 'p', html: 'Diese Datenschutzerklarung gilt ab dem 29.03.2026.' },
        { type: 'h2', html: 'Wie erteilst du deine Einwilligung?' },
        {
          type: 'p',
          html: 'Durch die Nutzung der Anwendung willigst du in die Verarbeitung deiner Informationen durch den Dienstanbieter gemäß dieser Datenschutzerklarung in der jeweils aktuellen Fassung ein. "Verarbeitung" umfasst unter anderem das Verwenden von Cookies auf einem Computer oder mobilen Gerat sowie das Erheben, Speichern, Loschen, Nutzen, Kombinieren und Offenlegen von Informationen.',
        },
        { type: 'h2', html: 'Wie kannst du uns kontaktieren?' },
        {
          type: 'p',
          html: `Wenn du Fragen zum Datenschutz bei der Nutzung der Anwendung oder zu unseren Praktiken hast, kontaktiere den Dienstanbieter per E-Mail unter ${contact}.`,
        },
      ],
    },
    termsOfUse: {
      lastUpdated: '17. Marz 2026',
      blocks: [
        { type: 'h2', html: '1. Annahme der Bedingungen' },
        {
          type: 'p',
          html: 'Durch das Herunterladen, Installieren oder Nutzen von Revera ("App") erklarst du dich mit diesen Nutzungsbedingungen ("Bedingungen") einverstanden. Wenn du diesen Bedingungen nicht zustimmst, nutze die App nicht. Wir behalten uns vor, diese Bedingungen jederzeit zu andern. Die fortgesetzte Nutzung der App nach Anderungen gilt als Annahme der geanderten Bedingungen.',
        },
        { type: 'h2', html: '2. Nutzungsberechtigung' },
        {
          type: 'p',
          html: 'Du musst mindestens 13 Jahre alt sein, um die App zu nutzen. Wenn du unter 18 bist, bestatigst du, dass ein Elternteil oder gesetzlicher Vormund diese Bedingungen in deinem Namen gepruft und akzeptiert hat.',
        },
        { type: 'h2', html: '3. Beschreibung des Dienstes' },
        {
          type: 'p',
          html: 'Revera ist eine Entspannungs- und Ambient-Sound-Mixer-App, mit der Nutzer personalisierte Klangwelten fur Schlaf, Entspannung und Fokus erstellen konnen. Die App ist kein Medizinprodukt und erbringt keine medizinischen Leistungen.',
        },
        { type: 'h2', html: '4. Abonnement und Zahlung' },
        { type: 'h3', html: 'a) Kostenlose Testphase' },
        {
          type: 'p',
          html: 'Revera bietet eine kostenlose 3-Tage-Testphase. Wahrend der Testphase hast du kostenlos Zugriff auf alle Funktionen der App. Nach Ablauf der Testphase wird der Zugriff eingeschrankt, sofern du kein Abonnement abschließt. Zum Start der Testphase ist keine Zahlung erforderlich; Kosten entstehen nur, wenn du aktiv ein Abonnement auswählst.',
        },
        { type: 'h3', html: 'b) Abonnementplane' },
        { type: 'ul', items: ['Monatliches Abonnement fur $1.99/Monat', 'Jahrliches Abonnement fur $12.99/Jahr'] },
        { type: 'p', html: 'Preise konnen je nach Region variieren und sich andern.' },
        { type: 'h3', html: 'c) Automatische Verlangerung' },
        {
          type: 'p',
          html: 'Abonnements verlangern sich automatisch, sofern sie nicht mindestens 24 Stunden vor Ende des aktuellen Abrechnungszeitraums gekundigt werden. Dein Konto wird innerhalb von 24 Stunden vor Ende des aktuellen Zeitraums zum gleichen Preis belastet.',
        },
        { type: 'h3', html: 'd) Zahlung' },
        {
          type: 'p',
          html: 'Alle Zahlungen werden uber den Apple App Store oder Google Play Store abgewickelt. Revera erhebt oder speichert Zahlungsinformationen nicht direkt.',
        },
        { type: 'h3', html: 'e) Kundigung' },
        {
          type: 'p',
          html: 'Du kannst dein Abonnement jederzeit uber die Abonnement-Einstellungen deines Gerats kundigen (Apple: Einstellungen &gt; Apple-ID &gt; Abonnements; Android: Google Play Store &gt; Abonnements). Die Kundigung wird zum Ende des aktuellen Abrechnungszeitraums wirksam. Teilruckerstattungen fur nicht genutzte Zeitraume werden nicht gewahrt.',
        },
        { type: 'h3', html: 'f) Ruckerstattungen' },
        {
          type: 'p',
          html: 'Ruckerstattungsanfragen unterliegen den Richtlinien des Apple App Store oder Google Play Store. Bitte kontaktiere den jeweiligen Store fur Ruckerstattungsanfragen.',
        },
        { type: 'h2', html: '5. Geistiges Eigentum' },
        {
          type: 'p',
          html: 'Alle Inhalte der App, einschließlich Sounds, Musik, Grafiken, Logos, Icons, Benutzeroberflachendesign und Software, sind Eigentum von Revera oder seinen Lizenzgebern und durch geltende Gesetze zum geistigen Eigentum geschutzt. Du erhaltst eine beschrankte, nicht ausschließliche, nicht ubertragbare und widerrufliche Lizenz zur personlichen, nicht kommerziellen Nutzung der App.',
        },
        {
          type: 'p',
          html: 'Du darfst Inhalte der App nicht kopieren, verandern, verbreiten, verkaufen, vermieten, zuruckentwickeln oder abgeleitete Werke daraus erstellen.',
        },
        { type: 'h2', html: '6. Zulassige Nutzung' },
        { type: 'p', html: 'Du verpflichtest dich, Folgendes zu unterlassen:' },
        {
          type: 'ul',
          items: [
            'Sounds oder Inhalte der App weiterzuverbreiten, aufzuzeichnen oder kommerziell zu verwerten',
            'Zahlungs-, Sicherheits- oder Rechteverwaltungssysteme zu umgehen, zu deaktivieren oder zu beeintrachtigen',
            'die App fur rechtswidrige Zwecke zu nutzen',
            'unbefugten Zugriff auf Systeme oder Infrastruktur der App zu versuchen',
          ],
        },
        { type: 'h2', html: '7. Hinweis zu Gesundheit und Wohlbefinden' },
        { type: 'h3', html: 'a) Keine medizinische Beratung' },
        {
          type: 'p',
          html: 'Die App dient ausschließlich allgemeinen Wellness- und Entspannungszwecken. Sie diagnostiziert, behandelt, heilt oder verhindert keine Krankheit, medizinische Erkrankung oder Schlafstorung.',
        },
        { type: 'h3', html: 'b) Kein Ersatz fur professionelle Behandlung' },
        {
          type: 'p',
          html: 'Die App ersetzt keine professionelle medizinische Beratung, Diagnose oder Behandlung. Wenn du Bedenken hinsichtlich Schlaf oder Gesundheit hast, wende dich an qualifiziertes medizinisches Fachpersonal.',
        },
        { type: 'h3', html: 'c) Keine Ergebnisgarantie' },
        {
          type: 'p',
          html: 'Revera garantiert nicht, dass die App deine Schlafqualitat verbessert oder ein bestimmtes Ergebnis erzielt. Ergebnisse konnen individuell variieren.',
        },
        { type: 'h2', html: '8. Haftungsbeschrankung' },
        {
          type: 'p',
          html: 'Soweit gesetzlich zulassig haftet Revera nicht fur indirekte, zufallige, besondere, Folge- oder Strafschaden, einschließlich Daten-, Umsatz-, Gewinn- oder Firmenwertverlusten sowie gesundheitsbezogener Folgen, die aus oder im Zusammenhang mit der Nutzung der App entstehen.',
        },
        { type: 'h2', html: '9. Gewahrleistungsausschluss' },
        {
          type: 'p',
          html: 'Die App wird "wie besehen" und "wie verfugbar" ohne Gewahrleistungen jeglicher Art bereitgestellt, weder ausdrucklich noch stillschweigend oder gesetzlich. Revera schließt insbesondere Gewahrleistungen der Marktgangigkeit, Eignung fur einen bestimmten Zweck und Nichtverletzung von Rechten aus.',
        },
        { type: 'h2', html: '10. Verfugbarkeit von Inhalten' },
        {
          type: 'p',
          html: 'Revera behalt sich vor, Sounds und Funktionen jederzeit ohne vorherige Ankundigung zu andern, hinzuzufugen oder zu entfernen. Eine dauerhafte Verfugbarkeit bestimmter Sounds oder Funktionen wird nicht garantiert.',
        },
        { type: 'h2', html: '11. Beendigung' },
        {
          type: 'p',
          html: 'Wir konnen deinen Zugriff auf die App jederzeit ohne Vorankundigung sperren oder beenden, wenn dein Verhalten nach unserer Einschatzung gegen diese Bedingungen verstößt oder Nutzern, uns oder Dritten schadet. Mit der Beendigung erlischt deine Lizenz zur Nutzung der App sofort.',
        },
        { type: 'h2', html: '12. Freistellung' },
        {
          type: 'p',
          html: 'Du verpflichtest dich, Revera sowie dessen Verantwortliche, Mitarbeitende und verbundene Unternehmen von Anspruchen, Schaden, Verlusten, Verbindlichkeiten, Kosten oder Aufwendungen freizustellen, die aus deiner Nutzung der App oder deiner Verletzung dieser Bedingungen entstehen.',
        },
        { type: 'h2', html: '13. Anwendbares Recht und Gerichtsstand' },
        {
          type: 'p',
          html: 'Diese Bedingungen unterliegen dem Recht der Bundesrepublik Deutschland. Fur Streitigkeiten aus diesen Bedingungen sind die Gerichte in Nordrhein-Westfalen zustandig, unbeschadet zwingender Verbraucherschutzvorschriften deines Aufenthaltslandes.',
        },
        { type: 'h2', html: '14. Apple und Google als Drittbegunstigte' },
        {
          type: 'p',
          html: 'Du erkennst an, dass diese Bedingungen ausschließlich zwischen dir und Revera gelten und nicht mit Apple Inc. oder Google LLC. Apple Inc. und seine Tochtergesellschaften sind jedoch Drittbegunstigte dieser Bedingungen und konnen diese nach deiner Annahme gegen dich durchsetzen.',
        },
        { type: 'h2', html: '15. Salvatorische Klausel' },
        {
          type: 'p',
          html: 'Sollte eine Bestimmung dieser Bedingungen undurchsetzbar oder unwirksam sein, wird sie im erforderlichen Mindestumfang beschrankt oder gestrichen; die ubrigen Bestimmungen bleiben voll wirksam.',
        },
        { type: 'h2', html: '16. Gesamte Vereinbarung' },
        {
          type: 'p',
          html: 'Diese Bedingungen bilden zusammen mit der Datenschutzerklarung die gesamte Vereinbarung zwischen dir und Revera bezuglich der Nutzung der App und ersetzen alle vorherigen Vereinbarungen.',
        },
        { type: 'h2', html: '17. Kontakt' },
        { type: 'p', html: `Bei Fragen zu diesen Bedingungen kontaktiere uns unter: ${termsContact}` },
      ],
    },
    legalNotice: {
      blocks: [
        { type: 'h2', html: 'Angaben gemaß &sect; 5 TMG' },
        {
          type: 'p',
          html: '<strong>ESOciate - Eser Kayali</strong><br />Im Sudfeld 32<br />45897 Gelsenkirchen<br />Deutschland',
        },
        { type: 'h2', html: 'Kontakt' },
        { type: 'p', html: `E-Mail: ${contact}` },
        { type: 'h2', html: 'Verantwortlich fur den Inhalt gemaß &sect; 55 Abs. 2 RStV' },
        {
          type: 'p',
          html: '<strong>Eser Kayali</strong><br />Im Sudfeld 32<br />45897 Gelsenkirchen<br />Deutschland',
        },
        { type: 'h2', html: 'Haftungsausschluss' },
        { type: 'h3', html: 'Haftung fur Inhalte' },
        {
          type: 'p',
          html: 'Die Inhalte unserer Seiten wurden mit großer Sorgfalt erstellt. Fur Richtigkeit, Vollstandigkeit und Aktualitat konnen wir jedoch keine Gewahr ubernehmen. Als Diensteanbieter sind wir fur eigene Inhalte nach den allgemeinen Gesetzen verantwortlich, jedoch nicht verpflichtet, ubermittelte oder gespeicherte fremde Informationen zu uberwachen.',
        },
        { type: 'h3', html: 'Haftung fur Links' },
        {
          type: 'p',
          html: 'Unsere Website kann Links zu externen Websites Dritter enthalten, auf deren Inhalte wir keinen Einfluss haben. Fur diese fremden Inhalte ubernehmen wir keine Haftung. Verantwortlich ist stets der jeweilige Anbieter oder Betreiber der verlinkten Seiten.',
        },
        { type: 'h3', html: 'Urheberrecht' },
        {
          type: 'p',
          html: 'Die durch die Seitenbetreiber erstellten Inhalte und Werke unterliegen dem deutschen Urheberrecht. Vervielfaltigung, Bearbeitung, Verbreitung oder Verwertung außerhalb der Grenzen des Urheberrechts bedurfen der schriftlichen Zustimmung des jeweiligen Autors oder Erstellers.',
        },
      ],
    },
  },
  es: {
    privacyPolicy: {
      lastUpdated: '17 de marzo de 2026',
      blocks: [
        { type: 'p', html: 'Esta politica de privacidad se aplica a la app movil Revera (en adelante, la "Aplicacion"), desarrollada por ESOciate - Eser Kayali (en adelante, el "Proveedor del servicio") como servicio comercial. Este servicio se proporciona "tal cual".' },
        { type: 'h2', html: 'Que informacion obtiene la Aplicacion y como se utiliza?' },
        { type: 'p', html: 'La Aplicacion obtiene la informacion que proporcionas al descargarla y registrarte. El registro no es obligatorio, aunque algunas funciones podrian no estar disponibles sin registrarte.' },
        { type: 'p', html: 'El Proveedor del servicio tambien puede utilizar la informacion proporcionada para contactarte ocasionalmente con informacion importante, avisos requeridos y promociones de marketing.' },
        { type: 'h2', html: 'Que informacion recopila automaticamente la Aplicacion?' },
        { type: 'p', html: 'La Aplicacion puede recopilar automaticamente cierta informacion, como el tipo de dispositivo movil, identificador unico del dispositivo, direccion IP, sistema operativo movil, tipo de navegador movil e informacion sobre el uso de la Aplicacion.' },
        { type: 'h2', html: 'La Aplicacion recopila informacion precisa de ubicacion en tiempo real?' },
        { type: 'p', html: 'Esta Aplicacion no recopila informacion precisa sobre la ubicacion de tu dispositivo movil.' },
        { type: 'h2', html: 'La Aplicacion utiliza tecnologias de Inteligencia Artificial (IA)?' },
        { type: 'p', html: 'La Aplicacion no utiliza tecnologias de Inteligencia Artificial (IA) para procesar tus datos ni para ofrecer funciones.' },
        { type: 'h2', html: 'Terceros ven o tienen acceso a la informacion obtenida por la Aplicacion?' },
        { type: 'p', html: 'Solo se transmiten periodicamente datos agregados y anonimizados a servicios externos para ayudar al Proveedor del servicio a mejorar la Aplicacion y el servicio. El Proveedor del servicio puede compartir tu informacion con terceros de las formas descritas en esta politica.' },
        { type: 'p', html: 'La Aplicacion utiliza servicios de terceros que tienen sus propias politicas de privacidad. Estos son los proveedores utilizados:' },
        { type: 'ul', items: [expo, revenueCat] },
        { type: 'p', html: 'El Proveedor del servicio puede divulgar informacion proporcionada por el usuario e informacion recopilada automaticamente:' },
        { type: 'ul', items: ['cuando lo exija la ley o un proceso legal similar;', 'cuando considere de buena fe que la divulgacion es necesaria para proteger sus derechos, tu seguridad o la de otros, investigar fraude o responder a una solicitud gubernamental;', 'con proveedores de servicios de confianza que trabajan en su nombre, no tienen uso independiente de la informacion y aceptan cumplir esta politica.'] },
        { type: 'h2', html: 'Cuales son mis derechos de exclusion?' },
        { type: 'p', html: 'Puedes detener toda recopilacion de informacion desinstalando la Aplicacion mediante los procesos estandar de tu dispositivo o de la tienda de aplicaciones.' },
        { type: 'h2', html: 'Cual es la politica de retencion de datos y como puedes gestionar tu informacion?' },
        { type: 'p', html: `El Proveedor del servicio conservara los datos proporcionados mientras uses la Aplicacion y durante un periodo razonable posterior. La informacion recopilada automaticamente se conservara hasta 24 meses y despues podra almacenarse de forma agregada. Para solicitar la eliminacion de datos proporcionados, contacta con ${contact}.` },
        { type: 'h2', html: 'Como aborda la Aplicacion la privacidad de los menores?' },
        { type: 'p', html: 'El Proveedor del servicio no utiliza la Aplicacion para solicitar datos conscientemente a menores de 13 anos ni para dirigirles marketing.' },
        { type: 'p', html: `La Aplicacion no esta dirigida a menores de 13 anos. Si el Proveedor del servicio descubre que un menor de 13 anos ha proporcionado datos personales, los eliminara inmediatamente. Si eres padre, madre o tutor y sabes que tu hijo ha proporcionado informacion personal, contacta con ${contact}.` },
        { type: 'h2', html: 'Como se mantiene segura tu informacion?' },
        { type: 'p', html: 'El Proveedor del servicio se preocupa por proteger la confidencialidad de tu informacion y aplica medidas fisicas, electronicas y organizativas. El acceso se limita a empleados y contratistas autorizados que necesitan la informacion para operar, desarrollar o mejorar la Aplicacion. Ningun sistema de seguridad puede impedir todas las brechas posibles.' },
        { type: 'h2', html: 'Como se te informara de cambios en esta politica?' },
        { type: 'p', html: 'Esta politica puede actualizarse ocasionalmente. El Proveedor del servicio notificara los cambios actualizando esta pagina. Te recomendamos revisarla regularmente; el uso continuado supone la aceptacion de los cambios.' },
        { type: 'p', html: 'Esta politica de privacidad es efectiva desde el 2026-03-29.' },
        { type: 'h2', html: 'Como das tu consentimiento?' },
        { type: 'p', html: 'Al usar la Aplicacion, consientes el procesamiento de tu informacion conforme a esta politica, ahora y segun sea modificada. "Procesamiento" incluye recopilar, almacenar, eliminar, usar, combinar y divulgar informacion.' },
        { type: 'h2', html: 'Como puedes contactarnos?' },
        { type: 'p', html: `Si tienes preguntas sobre privacidad al usar la Aplicacion o sobre nuestras practicas, contacta al Proveedor del servicio en ${contact}.` },
      ],
    },
    termsOfUse: {
      lastUpdated: '17 de marzo de 2026',
      blocks: [
        { type: 'h2', html: '1. Aceptacion de los terminos' },
        { type: 'p', html: 'Al descargar, instalar o usar Revera ("la App"), aceptas estos Terminos de uso ("Terminos"). Si no estas de acuerdo, no uses la App. Podemos modificar estos Terminos en cualquier momento; el uso continuado tras los cambios implica aceptacion.' },
        { type: 'h2', html: '2. Elegibilidad' },
        { type: 'p', html: 'Debes tener al menos 13 anos para usar la App. Si eres menor de 18, confirmas que un padre, madre o tutor legal ha revisado y aceptado estos Terminos en tu nombre.' },
        { type: 'h2', html: '3. Descripcion del servicio' },
        { type: 'p', html: 'Revera es una app de relajacion y mezcla de sonidos ambientales para crear paisajes sonoros personalizados para dormir, relajarse y concentrarse. La App no es un dispositivo medico ni ofrece servicios medicos.' },
        { type: 'h2', html: '4. Suscripcion y pago' },
        { type: 'h3', html: 'a) Prueba gratuita' },
        { type: 'p', html: 'Revera ofrece una prueba gratuita de 3 dias con acceso a todas las funciones. Al finalizar, el acceso se restringe salvo que elijas suscribirte. No se requiere pago para iniciar la prueba y no se te cobrara salvo que selecciones activamente un plan.' },
        { type: 'h3', html: 'b) Planes de suscripcion' },
        { type: 'ul', items: ['Suscripcion mensual de $1.99/mes', 'Suscripcion anual de $12.99/ano'] },
        { type: 'p', html: 'Los precios pueden variar por region y estar sujetos a cambios.' },
        { type: 'h3', html: 'c) Renovacion automatica' },
        { type: 'p', html: 'Las suscripciones se renuevan automaticamente salvo cancelacion al menos 24 horas antes del fin del periodo vigente. La cuenta se cargara dentro de las 24 horas previas al final del periodo al mismo precio.' },
        { type: 'h3', html: 'd) Pago' },
        { type: 'p', html: 'Todos los pagos se procesan a traves de Apple App Store o Google Play Store. Revera no recopila ni almacena directamente informacion de pago.' },
        { type: 'h3', html: 'e) Cancelacion' },
        { type: 'p', html: 'Puedes cancelar la suscripcion en cualquier momento desde los ajustes de suscripciones de tu dispositivo. La cancelacion surte efecto al final del periodo vigente; no se ofrecen reembolsos parciales.' },
        { type: 'h3', html: 'f) Reembolsos' },
        { type: 'p', html: 'Las solicitudes de reembolso estan sujetas a las politicas de Apple App Store o Google Play Store.' },
        { type: 'h2', html: '5. Propiedad intelectual' },
        { type: 'p', html: 'Todo el contenido de la App, incluidos sonidos, musica, graficos, logotipos, iconos, diseno de interfaz y software, pertenece a Revera o a sus licenciantes y esta protegido por las leyes aplicables. Se te concede una licencia limitada, no exclusiva, intransferible y revocable para uso personal y no comercial.' },
        { type: 'p', html: 'No puedes copiar, modificar, distribuir, vender, alquilar, aplicar ingenieria inversa ni crear obras derivadas del contenido de la App.' },
        { type: 'h2', html: '6. Uso aceptable' },
        { type: 'p', html: 'Aceptas no:' },
        { type: 'ul', items: ['redistribuir, grabar o explotar comercialmente sonidos o contenido de la App', 'eludir o interferir con funciones de pago, seguridad o gestion de derechos digitales', 'usar la App con fines ilegales', 'intentar obtener acceso no autorizado a sistemas o infraestructura de la App'] },
        { type: 'h2', html: '7. Aviso de salud y bienestar' },
        { type: 'h3', html: 'a) No es consejo medico' },
        { type: 'p', html: 'La App esta destinada solo a bienestar general y relajacion. No diagnostica, trata, cura ni previene enfermedades, condiciones medicas o trastornos del sueno.' },
        { type: 'h3', html: 'b) No sustituye atencion profesional' },
        { type: 'p', html: 'La App no sustituye consejo, diagnostico o tratamiento medico profesional. Si tienes preocupaciones sobre tu sueno o salud, consulta a un profesional cualificado.' },
        { type: 'h3', html: 'c) Sin garantia de resultados' },
        { type: 'p', html: 'Revera no garantiza que la App mejore tu calidad de sueno ni produzca un resultado especifico. Los resultados pueden variar.' },
        { type: 'h2', html: '8. Limitacion de responsabilidad' },
        { type: 'p', html: 'En la maxima medida permitida por la ley, Revera no sera responsable de danos indirectos, incidentales, especiales, consecuentes o punitivos derivados del uso de la App.' },
        { type: 'h2', html: '9. Exclusion de garantias' },
        { type: 'p', html: 'La App se proporciona "tal cual" y "segun disponibilidad", sin garantias de ningun tipo, expresas, implicitas o legales. No garantizamos que la App sea ininterrumpida o libre de errores.' },
        { type: 'h2', html: '10. Disponibilidad de contenido' },
        { type: 'p', html: 'Revera puede modificar, anadir o eliminar sonidos y funciones en cualquier momento sin aviso previo y no garantiza la disponibilidad permanente de ningun contenido especifico.' },
        { type: 'h2', html: '11. Terminacion' },
        { type: 'p', html: 'Podemos suspender o terminar tu acceso a la App en cualquier momento, sin aviso, por conductas que consideremos contrarias a estos Terminos o perjudiciales.' },
        { type: 'h2', html: '12. Indemnizacion' },
        { type: 'p', html: 'Aceptas indemnizar y mantener indemne a Revera frente a reclamaciones, danos, perdidas, responsabilidades, costes o gastos relacionados con tu uso de la App o incumplimiento de estos Terminos.' },
        { type: 'h2', html: '13. Ley aplicable y jurisdiccion' },
        { type: 'p', html: 'Estos Terminos se rigen por las leyes de la Republica Federal de Alemania. Los tribunales de Renania del Norte-Westfalia tendran jurisdiccion, sin perjuicio de normas obligatorias de proteccion al consumidor.' },
        { type: 'h2', html: '14. Apple y Google como terceros beneficiarios' },
        { type: 'p', html: 'Reconoces que estos Terminos son entre tu y Revera, no con Apple Inc. ni Google LLC. Apple Inc. y sus filiales son terceros beneficiarios y pueden hacer cumplir estos Terminos.' },
        { type: 'h2', html: '15. Divisibilidad' },
        { type: 'p', html: 'Si alguna disposicion resulta invalida o inaplicable, se limitara o eliminara en la medida minima necesaria y las demas disposiciones seguiran vigentes.' },
        { type: 'h2', html: '16. Acuerdo completo' },
        { type: 'p', html: 'Estos Terminos, junto con la Politica de privacidad, constituyen el acuerdo completo entre tu y Revera sobre el uso de la App.' },
        { type: 'h2', html: '17. Contacto' },
        { type: 'p', html: `Si tienes preguntas sobre estos Terminos, contactanos en: ${termsContact}` },
      ],
    },
    legalNotice: {
      blocks: [
        { type: 'h2', html: 'Informacion conforme al &sect; 5 TMG' },
        { type: 'p', html: '<strong>ESOciate - Eser Kayali</strong><br />Im Sudfeld 32<br />45897 Gelsenkirchen<br />Alemania' },
        { type: 'h2', html: 'Contacto' },
        { type: 'p', html: `E-Mail: ${contact}` },
        { type: 'h2', html: 'Responsable del contenido conforme al &sect; 55 Abs. 2 RStV' },
        { type: 'p', html: '<strong>Eser Kayali</strong><br />Im Sudfeld 32<br />45897 Gelsenkirchen<br />Alemania' },
        { type: 'h2', html: 'Aviso legal' },
        { type: 'h3', html: 'Responsabilidad por el contenido' },
        { type: 'p', html: 'Los contenidos de nuestras paginas se han creado con el mayor cuidado. No obstante, no podemos garantizar su exactitud, integridad o actualidad. Como proveedor de servicios, somos responsables de nuestros propios contenidos conforme a la legislacion general.' },
        { type: 'h3', html: 'Responsabilidad por enlaces' },
        { type: 'p', html: 'Nuestro sitio puede contener enlaces a sitios externos de terceros sobre cuyo contenido no tenemos influencia. Por ello no asumimos responsabilidad por esos contenidos externos.' },
        { type: 'h3', html: 'Derechos de autor' },
        { type: 'p', html: 'Los contenidos y obras creados por los operadores de este sitio estan sujetos a la legislacion alemana de derechos de autor. Cualquier uso fuera de los limites legales requiere el consentimiento escrito del autor o creador correspondiente.' },
      ],
    },
  },
  fr: {
    privacyPolicy: {
      lastUpdated: '17 mars 2026',
      blocks: [
        { type: 'p', html: 'La presente politique de confidentialite s applique a l application mobile Revera (ci-apres l "Application"), developpee par ESOciate - Eser Kayali (ci-apres le "Fournisseur de service") en tant que service commercial. Ce service est fourni "tel quel".' },
        { type: 'h2', html: 'Quelles informations l Application obtient-elle et comment sont-elles utilisees ?' },
        { type: 'p', html: 'L Application obtient les informations que vous fournissez lors du telechargement et de l inscription. L inscription n est pas obligatoire, mais certaines fonctionnalites peuvent ne pas etre disponibles sans inscription.' },
        { type: 'p', html: 'Le Fournisseur de service peut egalement utiliser les informations fournies pour vous contacter ponctuellement avec des informations importantes, des avis requis et des offres marketing.' },
        { type: 'h2', html: 'Quelles informations l Application collecte-t-elle automatiquement ?' },
        { type: 'p', html: 'L Application peut collecter automatiquement certaines informations, notamment le type d appareil mobile, l identifiant unique de l appareil, l adresse IP, le systeme d exploitation mobile, le type de navigateur mobile et des informations sur votre utilisation de l Application.' },
        { type: 'h2', html: 'L Application collecte-t-elle la localisation precise en temps reel ?' },
        { type: 'p', html: 'Cette Application ne collecte pas d informations precises sur la localisation de votre appareil mobile.' },
        { type: 'h2', html: 'L Application utilise-t-elle des technologies d Intelligence Artificielle (IA) ?' },
        { type: 'p', html: 'L Application n utilise pas de technologies d Intelligence Artificielle (IA) pour traiter vos donnees ou fournir des fonctionnalites.' },
        { type: 'h2', html: 'Des tiers voient-ils ou ont-ils acces aux informations obtenues ?' },
        { type: 'p', html: 'Seules des donnees agregees et anonymisees sont transmises periodiquement a des services externes afin d aider le Fournisseur de service a ameliorer l Application et son service. Les informations peuvent etre partagees avec des tiers selon les modalites decrites dans cette politique.' },
        { type: 'p', html: 'L Application utilise des services tiers disposant de leurs propres politiques de confidentialite :' },
        { type: 'ul', items: [expo, revenueCat] },
        { type: 'p', html: 'Le Fournisseur de service peut divulguer les informations fournies par l utilisateur et les informations collectees automatiquement :' },
        { type: 'ul', items: ['si la loi l exige ou dans le cadre d une procedure legale similaire ;', 's il estime de bonne foi que la divulgation est necessaire pour proteger ses droits, votre securite ou celle d autrui, enqueter sur une fraude ou repondre a une demande gouvernementale ;', 'a des prestataires de confiance agissant pour son compte, sans utilisation independante des informations et soumis aux regles de cette politique.'] },
        { type: 'h2', html: 'Quels sont mes droits d opposition ?' },
        { type: 'p', html: 'Vous pouvez mettre fin a toute collecte d informations en desinstallant l Application via les procedures standard de votre appareil ou de la boutique d applications.' },
        { type: 'h2', html: 'Quelle est la politique de conservation et comment gerer vos informations ?' },
        { type: 'p', html: `Le Fournisseur de service conserve les donnees fournies tant que vous utilisez l Application et pendant une periode raisonnable ensuite. Les informations collectees automatiquement sont conservees jusqu a 24 mois puis peuvent etre stockees sous forme agregee. Pour demander la suppression des donnees fournies, contactez ${contact}.` },
        { type: 'h2', html: 'Comment l Application protege-t-elle la vie privee des enfants ?' },
        { type: 'p', html: 'Le Fournisseur de service n utilise pas l Application pour solliciter sciemment des donnees d enfants de moins de 13 ans ni pour leur adresser du marketing.' },
        { type: 'p', html: `L Application ne s adresse pas aux personnes de moins de 13 ans. Si le Fournisseur de service decouvre qu un enfant de moins de 13 ans a fourni des informations personnelles, elles seront supprimees immediatement. Les parents ou tuteurs peuvent contacter ${contact}.` },
        { type: 'h2', html: 'Comment vos informations sont-elles securisees ?' },
        { type: 'p', html: 'Le Fournisseur de service prend la confidentialite de vos informations au serieux et applique des mesures physiques, electroniques et organisationnelles. L acces est limite aux personnes autorisees qui en ont besoin pour exploiter, developper ou ameliorer l Application. Aucun systeme de securite ne peut toutefois empecher toutes les violations possibles.' },
        { type: 'h2', html: 'Comment serez-vous informe des modifications ?' },
        { type: 'p', html: 'Cette politique peut etre mise a jour ponctuellement. Le Fournisseur de service vous informe des changements en mettant cette page a jour. Nous vous conseillons de la consulter regulierement; l utilisation continue vaut acceptation.' },
        { type: 'p', html: 'Cette politique de confidentialite est effective depuis le 2026-03-29.' },
        { type: 'h2', html: 'Comment donnez-vous votre consentement ?' },
        { type: 'p', html: 'En utilisant l Application, vous consentez au traitement de vos informations conforme a cette politique, actuelle et modifiee. Le traitement inclut notamment la collecte, le stockage, la suppression, l utilisation, la combinaison et la divulgation d informations.' },
        { type: 'h2', html: 'Comment nous contacter ?' },
        { type: 'p', html: `Pour toute question relative a la confidentialite ou a nos pratiques, contactez le Fournisseur de service a ${contact}.` },
      ],
    },
    termsOfUse: {
      lastUpdated: '17 mars 2026',
      blocks: [
        { type: 'h2', html: '1. Acceptation des conditions' },
        { type: 'p', html: 'En telechargeant, installant ou utilisant Revera ("l App"), vous acceptez ces Conditions d utilisation ("Conditions"). Si vous ne les acceptez pas, n utilisez pas l App. Nous pouvons modifier ces Conditions a tout moment; l utilisation continue vaut acceptation.' },
        { type: 'h2', html: '2. Eligibilite' },
        { type: 'p', html: 'Vous devez avoir au moins 13 ans pour utiliser l App. Si vous avez moins de 18 ans, vous confirmez qu un parent ou tuteur legal a examine et accepte ces Conditions en votre nom.' },
        { type: 'h2', html: '3. Description du service' },
        { type: 'p', html: 'Revera est une application de relaxation et de mixage de sons ambiants permettant de creer des ambiances sonores personnalisees pour le sommeil, la relaxation et la concentration. L App n est pas un dispositif medical et ne fournit pas de services medicaux.' },
        { type: 'h2', html: '4. Abonnement et paiement' },
        { type: 'h3', html: 'a) Essai gratuit' },
        { type: 'p', html: 'Revera propose un essai gratuit de 3 jours avec acces a toutes les fonctionnalites. A la fin de l essai, l acces est restreint sauf si vous choisissez un abonnement. Aucun paiement n est requis pour commencer et aucun frais n est facture sans choix actif d un plan.' },
        { type: 'h3', html: 'b) Formules d abonnement' },
        { type: 'ul', items: ['Abonnement mensuel a $1.99/mois', 'Abonnement annuel a $12.99/an'] },
        { type: 'p', html: 'Les prix peuvent varier selon les regions et etre modifies.' },
        { type: 'h3', html: 'c) Renouvellement automatique' },
        { type: 'p', html: 'Les abonnements se renouvellent automatiquement sauf annulation au moins 24 heures avant la fin de la periode en cours. Le compte est facture dans les 24 heures precedant la fin de la periode au meme prix.' },
        { type: 'h3', html: 'd) Paiement' },
        { type: 'p', html: 'Tous les paiements sont traites via l Apple App Store ou le Google Play Store. Revera ne collecte ni ne stocke directement les informations de paiement.' },
        { type: 'h3', html: 'e) Annulation' },
        { type: 'p', html: 'Vous pouvez annuler votre abonnement a tout moment via les parametres d abonnement de votre appareil. L annulation prend effet a la fin de la periode en cours; aucun remboursement partiel n est fourni.' },
        { type: 'h3', html: 'f) Remboursements' },
        { type: 'p', html: 'Les demandes de remboursement sont soumises aux politiques de l Apple App Store ou du Google Play Store.' },
        { type: 'h2', html: '5. Propriete intellectuelle' },
        { type: 'p', html: 'Tout le contenu de l App, y compris sons, musique, graphismes, logos, icones, interface et logiciel, appartient a Revera ou a ses concédants et est protege par les lois applicables. Une licence limitee, non exclusive, non transferable et revocable vous est accordee pour un usage personnel et non commercial.' },
        { type: 'p', html: 'Vous ne pouvez pas copier, modifier, distribuer, vendre, louer, effectuer de l ingenierie inverse ni creer des oeuvres derivees du contenu de l App.' },
        { type: 'h2', html: '6. Utilisation acceptable' },
        { type: 'p', html: 'Vous acceptez de ne pas :' },
        { type: 'ul', items: ['redistribuer, enregistrer ou exploiter commercialement les sons ou contenus de l App', 'contourner ou perturber les fonctions de paiement, de securite ou de gestion des droits', 'utiliser l App a des fins illegales', 'tenter un acces non autorise aux systemes ou a l infrastructure de l App'] },
        { type: 'h2', html: '7. Avertissement sante et bien-etre' },
        { type: 'h3', html: 'a) Pas un avis medical' },
        { type: 'p', html: 'L App est destinee uniquement au bien-etre general et a la relaxation. Elle ne diagnostique, traite, guerit ni previent aucune maladie, affection medicale ou trouble du sommeil.' },
        { type: 'h3', html: 'b) Ne remplace pas les soins professionnels' },
        { type: 'p', html: 'L App ne remplace pas un avis, diagnostic ou traitement medical professionnel. En cas de question sur votre sommeil ou votre sante, consultez un professionnel qualifie.' },
        { type: 'h3', html: 'c) Aucune garantie de resultats' },
        { type: 'p', html: 'Revera ne garantit pas que l App ameliorera votre sommeil ou produira un resultat specifique. Les resultats peuvent varier.' },
        { type: 'h2', html: '8. Limitation de responsabilite' },
        { type: 'p', html: 'Dans toute la mesure permise par la loi, Revera ne saurait etre responsable des dommages indirects, accessoires, speciaux, consecutifs ou punitifs lies a l utilisation de l App.' },
        { type: 'h2', html: '9. Exclusion de garanties' },
        { type: 'p', html: 'L App est fournie "telle quelle" et "selon disponibilite", sans garantie d aucune sorte. Nous ne garantissons pas que l App sera ininterrompue ou exempte d erreurs.' },
        { type: 'h2', html: '10. Disponibilite du contenu' },
        { type: 'p', html: 'Revera peut modifier, ajouter ou supprimer des sons et fonctionnalites a tout moment sans preavis et ne garantit pas la disponibilite permanente d un contenu specifique.' },
        { type: 'h2', html: '11. Resiliation' },
        { type: 'p', html: 'Nous pouvons suspendre ou resilier votre acces a l App a tout moment, sans preavis, en cas de conduite contraire a ces Conditions ou prejudiciable.' },
        { type: 'h2', html: '12. Indemnisation' },
        { type: 'p', html: 'Vous acceptez d indemniser et de degager Revera de toute reclamation, dommage, perte, responsabilite, cout ou depense lie a votre utilisation de l App ou a votre violation de ces Conditions.' },
        { type: 'h2', html: '13. Droit applicable et juridiction' },
        { type: 'p', html: 'Ces Conditions sont regies par le droit de la Republique federale d Allemagne. Les tribunaux de Rhenanie-du-Nord-Westphalie sont competents, sans prejudice des dispositions imperatives de protection des consommateurs.' },
        { type: 'h2', html: '14. Apple et Google tiers beneficiaires' },
        { type: 'p', html: 'Vous reconnaissez que ces Conditions vous lient a Revera uniquement, et non a Apple Inc. ou Google LLC. Apple Inc. et ses filiales sont toutefois tiers beneficiaires et peuvent les faire appliquer.' },
        { type: 'h2', html: '15. Divisibilite' },
        { type: 'p', html: 'Si une disposition est invalide ou inapplicable, elle sera limitee ou supprimee dans la mesure minimale necessaire et les autres dispositions resteront en vigueur.' },
        { type: 'h2', html: '16. Accord integral' },
        { type: 'p', html: 'Ces Conditions, avec la Politique de confidentialite, constituent l accord integral entre vous et Revera concernant l utilisation de l App.' },
        { type: 'h2', html: '17. Contact' },
        { type: 'p', html: `Pour toute question sur ces Conditions, contactez-nous a : ${termsContact}` },
      ],
    },
    legalNotice: {
      blocks: [
        { type: 'h2', html: 'Informations conformes au &sect; 5 TMG' },
        { type: 'p', html: '<strong>ESOciate - Eser Kayali</strong><br />Im Sudfeld 32<br />45897 Gelsenkirchen<br />Allemagne' },
        { type: 'h2', html: 'Contact' },
        { type: 'p', html: `E-mail : ${contact}` },
        { type: 'h2', html: 'Responsable du contenu selon le &sect; 55 Abs. 2 RStV' },
        { type: 'p', html: '<strong>Eser Kayali</strong><br />Im Sudfeld 32<br />45897 Gelsenkirchen<br />Allemagne' },
        { type: 'h2', html: 'Avertissement legal' },
        { type: 'h3', html: 'Responsabilite du contenu' },
        { type: 'p', html: 'Les contenus de nos pages ont ete crees avec le plus grand soin. Nous ne pouvons toutefois garantir leur exactitude, exhaustivite ou actualite. En tant que fournisseur de services, nous sommes responsables de nos propres contenus conformement aux lois generales.' },
        { type: 'h3', html: 'Responsabilite des liens' },
        { type: 'p', html: 'Notre site peut contenir des liens vers des sites externes de tiers dont nous ne controlons pas le contenu. Nous n assumons donc aucune responsabilite pour ces contenus externes.' },
        { type: 'h3', html: 'Droit d auteur' },
        { type: 'p', html: 'Les contenus et oeuvres crees par les exploitants du site sont soumis au droit d auteur allemand. Toute utilisation au-dela des limites legales requiert l accord ecrit de l auteur ou createur concerne.' },
      ],
    },
  },
  it: {
    privacyPolicy: {
      lastUpdated: '17 marzo 2026',
      blocks: [
        { type: 'p', html: 'La presente informativa sulla privacy si applica all app mobile Revera (di seguito "Applicazione"), sviluppata da ESOciate - Eser Kayali (di seguito "Fornitore del servizio") come servizio commerciale. Il servizio viene fornito "cosi com e".' },
        { type: 'h2', html: 'Quali informazioni ottiene l Applicazione e come vengono usate?' },
        { type: 'p', html: 'L Applicazione acquisisce le informazioni che fornisci quando la scarichi e ti registri. La registrazione non e obbligatoria, ma alcune funzioni potrebbero non essere disponibili senza registrazione.' },
        { type: 'p', html: 'Il Fornitore del servizio puo usare le informazioni fornite anche per contattarti occasionalmente con informazioni importanti, avvisi richiesti e promozioni di marketing.' },
        { type: 'h2', html: 'Quali informazioni raccoglie automaticamente l Applicazione?' },
        { type: 'p', html: 'L Applicazione puo raccogliere automaticamente informazioni quali tipo di dispositivo mobile, ID univoco del dispositivo, indirizzo IP, sistema operativo mobile, tipo di browser mobile e dati sul modo in cui usi l Applicazione.' },
        { type: 'h2', html: 'L Applicazione raccoglie dati precisi sulla posizione in tempo reale?' },
        { type: 'p', html: 'Questa Applicazione non raccoglie informazioni precise sulla posizione del tuo dispositivo mobile.' },
        { type: 'h2', html: 'L Applicazione usa tecnologie di Intelligenza Artificiale (IA)?' },
        { type: 'p', html: 'L Applicazione non usa tecnologie di Intelligenza Artificiale (IA) per trattare i tuoi dati o fornire funzioni.' },
        { type: 'h2', html: 'Terze parti vedono o accedono alle informazioni ottenute?' },
        { type: 'p', html: 'Solo dati aggregati e anonimizzati vengono trasmessi periodicamente a servizi esterni per aiutare il Fornitore del servizio a migliorare l Applicazione e il servizio. Le informazioni possono essere condivise con terzi come descritto in questa informativa.' },
        { type: 'p', html: 'L Applicazione utilizza servizi di terze parti con proprie informative privacy:' },
        { type: 'ul', items: [expo, revenueCat] },
        { type: 'p', html: 'Il Fornitore del servizio puo divulgare informazioni fornite dall utente e raccolte automaticamente:' },
        { type: 'ul', items: ['quando richiesto dalla legge o da un procedimento legale simile;', 'quando ritiene in buona fede che la divulgazione sia necessaria per proteggere i propri diritti, la tua sicurezza o quella di altri, indagare frodi o rispondere a richieste governative;', 'a fornitori fidati che lavorano per suo conto e accettano di rispettare questa informativa.'] },
        { type: 'h2', html: 'Quali sono i miei diritti di opt-out?' },
        { type: 'p', html: 'Puoi interrompere ogni raccolta di informazioni disinstallando l Applicazione con le procedure standard del dispositivo o dello store.' },
        { type: 'h2', html: 'Qual e la politica di conservazione dei dati e come puoi gestire le informazioni?' },
        { type: 'p', html: `Il Fornitore del servizio conserva i dati forniti finche usi l Applicazione e per un periodo ragionevole successivo. Le informazioni raccolte automaticamente sono conservate fino a 24 mesi e poi possono essere archiviate in forma aggregata. Per richiedere la cancellazione dei dati forniti, contatta ${contact}.` },
        { type: 'h2', html: 'Come tutela l Applicazione la privacy dei minori?' },
        { type: 'p', html: 'Il Fornitore del servizio non usa consapevolmente l Applicazione per sollecitare dati da minori di 13 anni o fare marketing verso di loro.' },
        { type: 'p', html: `L Applicazione non e rivolta a minori di 13 anni. Se il Fornitore del servizio scopre che un minore di 13 anni ha fornito dati personali, li eliminera immediatamente. Genitori o tutori possono contattare ${contact}.` },
        { type: 'h2', html: 'Come vengono protette le tue informazioni?' },
        { type: 'p', html: 'Il Fornitore del servizio tutela la riservatezza delle informazioni con misure fisiche, elettroniche e organizzative. L accesso e limitato a personale autorizzato che ne ha bisogno per gestire, sviluppare o migliorare l Applicazione. Nessun sistema di sicurezza puo impedire tutte le possibili violazioni.' },
        { type: 'h2', html: 'Come sarai informato delle modifiche?' },
        { type: 'p', html: 'Questa informativa puo essere aggiornata di volta in volta. Il Fornitore del servizio informa delle modifiche aggiornando questa pagina. Ti consigliamo di consultarla regolarmente; l uso continuato implica accettazione.' },
        { type: 'p', html: 'Questa informativa sulla privacy e efficace dal 2026-03-29.' },
        { type: 'h2', html: 'Come presti il consenso?' },
        { type: 'p', html: 'Usando l Applicazione acconsenti al trattamento delle tue informazioni secondo questa informativa, ora e come modificata. Il trattamento include raccolta, conservazione, cancellazione, uso, combinazione e divulgazione di informazioni.' },
        { type: 'h2', html: 'Come contattarci?' },
        { type: 'p', html: `Per domande sulla privacy o sulle pratiche del servizio, contatta il Fornitore del servizio a ${contact}.` },
      ],
    },
    termsOfUse: {
      lastUpdated: '17 marzo 2026',
      blocks: [
        { type: 'h2', html: '1. Accettazione dei termini' },
        { type: 'p', html: 'Scaricando, installando o usando Revera ("App"), accetti questi Termini di utilizzo ("Termini"). Se non accetti, non usare l App. Possiamo modificarli in qualsiasi momento; l uso continuato dopo le modifiche costituisce accettazione.' },
        { type: 'h2', html: '2. Idoneita' },
        { type: 'p', html: 'Devi avere almeno 13 anni per usare l App. Se hai meno di 18 anni, confermi che un genitore o tutore legale ha letto e accettato questi Termini per tuo conto.' },
        { type: 'h2', html: '3. Descrizione del servizio' },
        { type: 'p', html: 'Revera e un app di rilassamento e mixer di suoni ambientali per creare paesaggi sonori personalizzati per sonno, relax e concentrazione. Non e un dispositivo medico e non fornisce servizi medici.' },
        { type: 'h2', html: '4. Abbonamento e pagamento' },
        { type: 'h3', html: 'a) Prova gratuita' },
        { type: 'p', html: 'Revera offre una prova gratuita di 3 giorni con accesso a tutte le funzioni. Al termine, l accesso sara limitato salvo sottoscrizione. Non e richiesto pagamento per iniziare e non sarai addebitato senza scegliere attivamente un piano.' },
        { type: 'h3', html: 'b) Piani di abbonamento' },
        { type: 'ul', items: ['Abbonamento mensile a $1.99/mese', 'Abbonamento annuale a $12.99/anno'] },
        { type: 'p', html: 'I prezzi possono variare per regione e cambiare.' },
        { type: 'h3', html: 'c) Rinnovo automatico' },
        { type: 'p', html: 'Gli abbonamenti si rinnovano automaticamente salvo cancellazione almeno 24 ore prima della fine del periodo corrente. L account sara addebitato entro le 24 ore precedenti la fine del periodo allo stesso prezzo.' },
        { type: 'h3', html: 'd) Pagamento' },
        { type: 'p', html: 'Tutti i pagamenti sono elaborati tramite Apple App Store o Google Play Store. Revera non raccoglie ne conserva direttamente dati di pagamento.' },
        { type: 'h3', html: 'e) Cancellazione' },
        { type: 'p', html: 'Puoi cancellare l abbonamento in qualsiasi momento dalle impostazioni abbonamenti del dispositivo. La cancellazione ha effetto alla fine del periodo corrente; non sono previsti rimborsi parziali.' },
        { type: 'h3', html: 'f) Rimborsi' },
        { type: 'p', html: 'Le richieste di rimborso sono soggette alle politiche di Apple App Store o Google Play Store.' },
        { type: 'h2', html: '5. Proprieta intellettuale' },
        { type: 'p', html: 'Tutti i contenuti dell App, inclusi suoni, musica, grafiche, loghi, icone, interfaccia e software, appartengono a Revera o ai suoi licenzianti e sono protetti dalle leggi applicabili. Ti viene concessa una licenza limitata, non esclusiva, non trasferibile e revocabile per uso personale e non commerciale.' },
        { type: 'p', html: 'Non puoi copiare, modificare, distribuire, vendere, noleggiare, decodificare o creare opere derivate dai contenuti dell App.' },
        { type: 'h2', html: '6. Uso accettabile' },
        { type: 'p', html: 'Accetti di non:' },
        { type: 'ul', items: ['ridistribuire, registrare o sfruttare commercialmente suoni o contenuti dell App', 'aggirare o interferire con funzioni di pagamento, sicurezza o gestione dei diritti', 'usare l App per scopi illeciti', 'tentare accessi non autorizzati a sistemi o infrastruttura dell App'] },
        { type: 'h2', html: '7. Avviso su salute e benessere' },
        { type: 'h3', html: 'a) Non e consulenza medica' },
        { type: 'p', html: 'L App e destinata solo a benessere generale e relax. Non diagnostica, tratta, cura o previene malattie, condizioni mediche o disturbi del sonno.' },
        { type: 'h3', html: 'b) Non sostituisce cure professionali' },
        { type: 'p', html: 'L App non sostituisce consulenza, diagnosi o trattamento medico professionale. Per dubbi su sonno o salute, consulta un professionista qualificato.' },
        { type: 'h3', html: 'c) Nessuna garanzia di risultati' },
        { type: 'p', html: 'Revera non garantisce miglioramenti della qualita del sonno o risultati specifici. I risultati possono variare.' },
        { type: 'h2', html: '8. Limitazione di responsabilita' },
        { type: 'p', html: 'Nella misura massima consentita dalla legge, Revera non sara responsabile per danni indiretti, incidentali, speciali, consequenziali o punitivi derivanti dall uso dell App.' },
        { type: 'h2', html: '9. Esclusione di garanzie' },
        { type: 'p', html: 'L App e fornita "cosi com e" e "secondo disponibilita", senza garanzie di alcun tipo. Non garantiamo funzionamento ininterrotto o assenza di errori.' },
        { type: 'h2', html: '10. Disponibilita dei contenuti' },
        { type: 'p', html: 'Revera puo modificare, aggiungere o rimuovere suoni e funzioni in qualsiasi momento senza preavviso e non garantisce la disponibilita permanente di contenuti specifici.' },
        { type: 'h2', html: '11. Risoluzione' },
        { type: 'p', html: 'Possiamo sospendere o terminare l accesso all App in qualsiasi momento, senza preavviso, per condotte che riteniamo violino questi Termini o siano dannose.' },
        { type: 'h2', html: '12. Manleva' },
        { type: 'p', html: 'Accetti di manlevare Revera da reclami, danni, perdite, responsabilita, costi o spese derivanti dal tuo uso dell App o dalla violazione di questi Termini.' },
        { type: 'h2', html: '13. Legge applicabile e foro' },
        { type: 'p', html: 'Questi Termini sono regolati dalle leggi della Repubblica Federale di Germania. I tribunali della Renania Settentrionale-Vestfalia avranno giurisdizione, fatte salve norme inderogabili di tutela dei consumatori.' },
        { type: 'h2', html: '14. Apple e Google come terzi beneficiari' },
        { type: 'p', html: 'Riconosci che questi Termini sono tra te e Revera, non con Apple Inc. o Google LLC. Apple Inc. e le sue controllate sono terzi beneficiari e possono farli valere.' },
        { type: 'h2', html: '15. Separabilita' },
        { type: 'p', html: 'Se una disposizione e invalida o inapplicabile, sara limitata o eliminata nella misura minima necessaria e le restanti disposizioni rimarranno efficaci.' },
        { type: 'h2', html: '16. Accordo completo' },
        { type: 'p', html: 'Questi Termini, insieme all Informativa sulla privacy, costituiscono l intero accordo tra te e Revera sull uso dell App.' },
        { type: 'h2', html: '17. Contatti' },
        { type: 'p', html: `Per domande su questi Termini, contattaci a: ${termsContact}` },
      ],
    },
    legalNotice: {
      blocks: [
        { type: 'h2', html: 'Informazioni ai sensi del &sect; 5 TMG' },
        { type: 'p', html: '<strong>ESOciate - Eser Kayali</strong><br />Im Sudfeld 32<br />45897 Gelsenkirchen<br />Germania' },
        { type: 'h2', html: 'Contatto' },
        { type: 'p', html: `E-mail: ${contact}` },
        { type: 'h2', html: 'Responsabile del contenuto ai sensi del &sect; 55 Abs. 2 RStV' },
        { type: 'p', html: '<strong>Eser Kayali</strong><br />Im Sudfeld 32<br />45897 Gelsenkirchen<br />Germania' },
        { type: 'h2', html: 'Note legali' },
        { type: 'h3', html: 'Responsabilita per i contenuti' },
        { type: 'p', html: 'I contenuti delle nostre pagine sono stati creati con la massima cura. Tuttavia non possiamo garantire correttezza, completezza o attualita. Come fornitore di servizi siamo responsabili dei nostri contenuti secondo le leggi generali.' },
        { type: 'h3', html: 'Responsabilita per i link' },
        { type: 'p', html: 'Il nostro sito puo contenere link a siti esterni di terzi sui cui contenuti non abbiamo influenza. Pertanto non assumiamo responsabilita per tali contenuti esterni.' },
        { type: 'h3', html: 'Diritto d autore' },
        { type: 'p', html: 'I contenuti e le opere creati dagli operatori del sito sono soggetti al diritto d autore tedesco. Qualsiasi uso oltre i limiti di legge richiede il consenso scritto del rispettivo autore o creatore.' },
      ],
    },
  },
  pt: {
    privacyPolicy: {
      lastUpdated: '17 de marco de 2026',
      blocks: [
        { type: 'p', html: 'Esta politica de privacidade aplica-se ao app movel Revera (doravante "Aplicativo"), desenvolvido pela ESOciate - Eser Kayali (doravante "Prestador do servico") como servico comercial. Este servico e fornecido "como esta".' },
        { type: 'h2', html: 'Quais informacoes o Aplicativo obtem e como elas sao usadas?' },
        { type: 'p', html: 'O Aplicativo obtem as informacoes que voce fornece ao baixa-lo e se registrar. O registro nao e obrigatorio, mas alguns recursos podem nao estar disponiveis sem registro.' },
        { type: 'p', html: 'O Prestador do servico tambem pode usar as informacoes fornecidas para entrar em contato ocasionalmente com informacoes importantes, avisos obrigatorios e promocoes de marketing.' },
        { type: 'h2', html: 'Quais informacoes o Aplicativo coleta automaticamente?' },
        { type: 'p', html: 'O Aplicativo pode coletar automaticamente certas informacoes, como tipo de dispositivo movel, ID unico do dispositivo, endereco IP, sistema operacional movel, tipo de navegador movel e dados sobre o uso do Aplicativo.' },
        { type: 'h2', html: 'O Aplicativo coleta localizacao precisa em tempo real?' },
        { type: 'p', html: 'Este Aplicativo nao coleta informacoes precisas sobre a localizacao do seu dispositivo movel.' },
        { type: 'h2', html: 'O Aplicativo usa tecnologias de Inteligencia Artificial (IA)?' },
        { type: 'p', html: 'O Aplicativo nao usa tecnologias de Inteligencia Artificial (IA) para processar seus dados ou fornecer recursos.' },
        { type: 'h2', html: 'Terceiros veem ou acessam informacoes obtidas pelo Aplicativo?' },
        { type: 'p', html: 'Apenas dados agregados e anonimizados sao transmitidos periodicamente a servicos externos para ajudar o Prestador do servico a melhorar o Aplicativo e o servico. As informacoes podem ser compartilhadas com terceiros conforme descrito nesta politica.' },
        { type: 'p', html: 'O Aplicativo utiliza servicos de terceiros com suas proprias politicas de privacidade:' },
        { type: 'ul', items: [expo, revenueCat] },
        { type: 'p', html: 'O Prestador do servico pode divulgar informacoes fornecidas pelo usuario e informacoes coletadas automaticamente:' },
        { type: 'ul', items: ['quando exigido por lei ou processo legal semelhante;', 'quando acreditar de boa-fe que a divulgacao e necessaria para proteger seus direitos, sua seguranca ou a de outros, investigar fraude ou responder a solicitacao governamental;', 'a prestadores confiaveis que trabalham em seu nome, sem uso independente das informacoes e sujeitos a esta politica.'] },
        { type: 'h2', html: 'Quais sao meus direitos de exclusao?' },
        { type: 'p', html: 'Voce pode interromper toda coleta de informacoes desinstalando o Aplicativo pelos processos padrao do dispositivo ou da loja de aplicativos.' },
        { type: 'h2', html: 'Qual e a politica de retencao de dados e como gerenciar suas informacoes?' },
        { type: 'p', html: `O Prestador do servico retera os dados fornecidos enquanto voce usar o Aplicativo e por periodo razoavel depois disso. As informacoes coletadas automaticamente serao retidas por ate 24 meses e depois podem ser armazenadas em forma agregada. Para solicitar exclusao dos dados fornecidos, entre em contato em ${contact}.` },
        { type: 'h2', html: 'Como o Aplicativo trata a privacidade de criancas?' },
        { type: 'p', html: 'O Prestador do servico nao usa conscientemente o Aplicativo para solicitar dados de criancas menores de 13 anos ou fazer marketing para elas.' },
        { type: 'p', html: `O Aplicativo nao se destina a menores de 13 anos. Se o Prestador do servico descobrir que uma crianca menor de 13 anos forneceu dados pessoais, eles serao excluidos imediatamente. Pais ou responsaveis podem contatar ${contact}.` },
        { type: 'h2', html: 'Como suas informacoes sao protegidas?' },
        { type: 'p', html: 'O Prestador do servico se preocupa com a confidencialidade das informacoes e aplica salvaguardas fisicas, eletronicas e organizacionais. O acesso e limitado a pessoas autorizadas que precisam das informacoes para operar, desenvolver ou melhorar o Aplicativo. Nenhum sistema de seguranca pode impedir todas as possiveis violacoes.' },
        { type: 'h2', html: 'Como voce sera informado sobre alteracoes?' },
        { type: 'p', html: 'Esta politica pode ser atualizada ocasionalmente. O Prestador do servico informara alteracoes atualizando esta pagina. Recomendamos consulta regular; o uso continuado significa aceitacao das mudancas.' },
        { type: 'p', html: 'Esta politica de privacidade entra em vigor em 2026-03-29.' },
        { type: 'h2', html: 'Como voce da consentimento?' },
        { type: 'p', html: 'Ao usar o Aplicativo, voce consente com o processamento das suas informacoes conforme esta politica, agora e conforme alterada. Processamento inclui coletar, armazenar, excluir, usar, combinar e divulgar informacoes.' },
        { type: 'h2', html: 'Como entrar em contato?' },
        { type: 'p', html: `Se tiver perguntas sobre privacidade ao usar o Aplicativo ou sobre nossas praticas, contate o Prestador do servico em ${contact}.` },
      ],
    },
    termsOfUse: {
      lastUpdated: '17 de marco de 2026',
      blocks: [
        { type: 'h2', html: '1. Aceitacao dos termos' },
        { type: 'p', html: 'Ao baixar, instalar ou usar o Revera ("App"), voce concorda com estes Termos de uso ("Termos"). Se nao concordar, nao use o App. Podemos modificar estes Termos a qualquer momento; o uso continuado apos alteracoes significa aceitacao.' },
        { type: 'h2', html: '2. Elegibilidade' },
        { type: 'p', html: 'Voce deve ter pelo menos 13 anos para usar o App. Se tiver menos de 18 anos, confirma que um dos pais ou responsavel legal revisou e aceitou estes Termos em seu nome.' },
        { type: 'h2', html: '3. Descricao do servico' },
        { type: 'p', html: 'Revera e um app de relaxamento e mixer de sons ambientes para criar paisagens sonoras personalizadas para sono, relaxamento e foco. O App nao e dispositivo medico e nao fornece servicos medicos.' },
        { type: 'h2', html: '4. Assinatura e pagamento' },
        { type: 'h3', html: 'a) Teste gratis' },
        { type: 'p', html: 'Revera oferece teste gratis de 3 dias com acesso a todos os recursos. Ao fim do teste, o acesso sera restrito salvo assinatura. Nenhum pagamento e necessario para iniciar e voce nao sera cobrado sem escolher ativamente um plano.' },
        { type: 'h3', html: 'b) Planos de assinatura' },
        { type: 'ul', items: ['Assinatura mensal por $1.99/mes', 'Assinatura anual por $12.99/ano'] },
        { type: 'p', html: 'Os precos podem variar por regiao e estar sujeitos a alteracao.' },
        { type: 'h3', html: 'c) Renovacao automatica' },
        { type: 'p', html: 'As assinaturas renovam automaticamente salvo cancelamento pelo menos 24 horas antes do fim do periodo atual. A conta sera cobrada nas 24 horas anteriores ao fim do periodo pelo mesmo preco.' },
        { type: 'h3', html: 'd) Pagamento' },
        { type: 'p', html: 'Todos os pagamentos sao processados pela Apple App Store ou Google Play Store. Revera nao coleta nem armazena diretamente informacoes de pagamento.' },
        { type: 'h3', html: 'e) Cancelamento' },
        { type: 'p', html: 'Voce pode cancelar a assinatura a qualquer momento nas configuracoes de assinatura do dispositivo. O cancelamento entra em vigor ao fim do periodo atual; nao ha reembolsos parciais.' },
        { type: 'h3', html: 'f) Reembolsos' },
        { type: 'p', html: 'Solicitacoes de reembolso seguem as politicas da Apple App Store ou Google Play Store.' },
        { type: 'h2', html: '5. Propriedade intelectual' },
        { type: 'p', html: 'Todo conteudo do App, incluindo sons, musica, graficos, logos, icones, interface e software, pertence ao Revera ou seus licenciadores e e protegido pelas leis aplicaveis. Voce recebe licenca limitada, nao exclusiva, intransferivel e revogavel para uso pessoal e nao comercial.' },
        { type: 'p', html: 'Voce nao pode copiar, modificar, distribuir, vender, alugar, fazer engenharia reversa ou criar obras derivadas do conteudo do App.' },
        { type: 'h2', html: '6. Uso aceitavel' },
        { type: 'p', html: 'Voce concorda em nao:' },
        { type: 'ul', items: ['redistribuir, gravar ou explorar comercialmente sons ou conteudo do App', 'burlar ou interferir em recursos de pagamento, seguranca ou gestao de direitos digitais', 'usar o App para finalidade ilegal', 'tentar acesso nao autorizado aos sistemas ou infraestrutura do App'] },
        { type: 'h2', html: '7. Aviso de saude e bem-estar' },
        { type: 'h3', html: 'a) Nao e aconselhamento medico' },
        { type: 'p', html: 'O App destina-se apenas a bem-estar geral e relaxamento. Ele nao diagnostica, trata, cura ou previne doencas, condicoes medicas ou disturbios do sono.' },
        { type: 'h3', html: 'b) Nao substitui cuidado profissional' },
        { type: 'p', html: 'O App nao substitui aconselhamento, diagnostico ou tratamento medico profissional. Se tiver preocupacoes sobre sono ou saude, consulte profissional qualificado.' },
        { type: 'h3', html: 'c) Sem garantia de resultados' },
        { type: 'p', html: 'Revera nao garante melhora da qualidade do sono ou resultado especifico. Resultados individuais podem variar.' },
        { type: 'h2', html: '8. Limitacao de responsabilidade' },
        { type: 'p', html: 'Na maxima medida permitida por lei, Revera nao sera responsavel por danos indiretos, incidentais, especiais, consequenciais ou punitivos decorrentes do uso do App.' },
        { type: 'h2', html: '9. Exclusao de garantias' },
        { type: 'p', html: 'O App e fornecido "como esta" e "conforme disponivel", sem garantias de qualquer tipo. Nao garantimos que o App sera ininterrupto ou livre de erros.' },
        { type: 'h2', html: '10. Disponibilidade de conteudo' },
        { type: 'p', html: 'Revera pode modificar, adicionar ou remover sons e recursos a qualquer momento sem aviso previo e nao garante disponibilidade permanente de qualquer conteudo especifico.' },
        { type: 'h2', html: '11. Encerramento' },
        { type: 'p', html: 'Podemos suspender ou encerrar seu acesso ao App a qualquer momento, sem aviso, por conduta que considerarmos violar estes Termos ou ser prejudicial.' },
        { type: 'h2', html: '12. Indenizacao' },
        { type: 'p', html: 'Voce concorda em indenizar e isentar Revera de reclamacoes, danos, perdas, responsabilidades, custos ou despesas relacionados ao uso do App ou violacao destes Termos.' },
        { type: 'h2', html: '13. Lei aplicavel e jurisdicao' },
        { type: 'p', html: 'Estes Termos sao regidos pelas leis da Republica Federal da Alemanha. Os tribunais da Renania do Norte-Vestfalia terao jurisdicao, sem prejuizo de normas obrigatorias de protecao ao consumidor.' },
        { type: 'h2', html: '14. Apple e Google como terceiros beneficiarios' },
        { type: 'p', html: 'Voce reconhece que estes Termos sao entre voce e Revera, nao com Apple Inc. ou Google LLC. Apple Inc. e suas subsidiarias sao terceiros beneficiarios e podem fazer cumprir estes Termos.' },
        { type: 'h2', html: '15. Separabilidade' },
        { type: 'p', html: 'Se alguma disposicao for invalida ou inexequivel, ela sera limitada ou removida na menor medida necessaria, e as demais permanecerao em vigor.' },
        { type: 'h2', html: '16. Acordo integral' },
        { type: 'p', html: 'Estes Termos, junto com a Politica de privacidade, constituem o acordo integral entre voce e Revera sobre o uso do App.' },
        { type: 'h2', html: '17. Contato' },
        { type: 'p', html: `Se tiver perguntas sobre estes Termos, entre em contato em: ${termsContact}` },
      ],
    },
    legalNotice: {
      blocks: [
        { type: 'h2', html: 'Informacoes de acordo com o &sect; 5 TMG' },
        { type: 'p', html: '<strong>ESOciate - Eser Kayali</strong><br />Im Sudfeld 32<br />45897 Gelsenkirchen<br />Alemanha' },
        { type: 'h2', html: 'Contato' },
        { type: 'p', html: `E-mail: ${contact}` },
        { type: 'h2', html: 'Responsavel pelo conteudo conforme &sect; 55 Abs. 2 RStV' },
        { type: 'p', html: '<strong>Eser Kayali</strong><br />Im Sudfeld 32<br />45897 Gelsenkirchen<br />Alemanha' },
        { type: 'h2', html: 'Aviso legal' },
        { type: 'h3', html: 'Responsabilidade pelo conteudo' },
        { type: 'p', html: 'Os conteudos de nossas paginas foram criados com grande cuidado. No entanto, nao podemos garantir exatidao, completude ou atualidade. Como prestador de servicos, somos responsaveis pelo nosso proprio conteudo conforme as leis gerais.' },
        { type: 'h3', html: 'Responsabilidade por links' },
        { type: 'p', html: 'Nosso site pode conter links para sites externos de terceiros sobre cujo conteudo nao temos influencia. Portanto, nao assumimos responsabilidade por esses conteudos externos.' },
        { type: 'h3', html: 'Direitos autorais' },
        { type: 'p', html: 'Os conteudos e obras criados pelos operadores do site estao sujeitos ao direito autoral alemao. Qualquer uso alem dos limites legais requer consentimento escrito do respectivo autor ou criador.' },
      ],
    },
  },
};
